title: Claire Lee
logo: /pics for profolio/æˆ‘.jpg
logo: /pics for profolio/me.jpg
logo: /pics for profolio/me1.jpg
logo: /pics for profolio/me2.jpg
#description: ğŸ“± +886 975252816 | âœ‰ï¸ claire940816@gmail.com 

show_downloads: true
theme: jekyll-theme-minimal
